# Generated by Django 5.1.4 on 2025-01-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='vehicleimages/default_car.png', upload_to='vehicleimages'),
        ),
    ]
